"""empty message

Revision ID: 1abeb3ff9017
Revises: 0b0bbe5d58fc
Create Date: 2023-03-29 00:42:38.654228

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1abeb3ff9017"
down_revision = "0b0bbe5d58fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project")
    # ### end Alembic commands ###
